# Base configs
baseurl: "http://http://nicoruiz.es/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "El mundo by Nico"
subtitle: "Conoce el mundo a través de mis dibujos"
author: "Nico"
header:
 title: "Mis dibujos"
 subtitle: "by Nico"
footer:
 name: "Hola, soy Nico"
 bio: "Soy un niño al que le encanta dibujar"
 github: ""
web_design: ""
